# [Info]
site_name: 个人主页 # 左上角标题
site_url: https://yyyxx6.github.io
site_author: yyyxx6
site_description: yyyxx6的个人主页

# [Navigtion]
nav:
  - Demo一级标题目录:
    - Demo/index.md

  - 测试中文:
    - 测试中文/index.md
    - 一级目录:
      - 测试中文/index.md
    - 二级目录1:
        - 测试中文/二级目录1/具体内容1.md
    - 二级目录2:
        - 测试中文/二级目录2/具体内容2.md

  - 开发:
    - DEV/index.md
    - Three:
      - DEV/Three/setup.md
    - App:
      - DEV/App/flutter-web-consideration.md
    - Flutter:
      - DEV/Flutter/commands.md
      - DEV/Flutter/dart-lint.md
      - DEV/Flutter/template.md
      - DEV/Flutter/state-management.md
    - React:
      - DEV/React/notes.md
    - 编程:
      - DEV/Programming/recommendation.md
      - DEV/Programming/my-feelings.md
      - Python:
        - DEV/Programming/Python/copy.md
        - DEV/Programming/Python/numpy-overview.md
      - Dart:
        - DEV/Programming/Dart/learning.md
      - Swift:
        - DEV/Programming/Swift/learning-resources.md
        - DEV/Programming/Swift/notes-basic-grammars.md
        - DEV/Programming/Swift/notes-language-guide.md
        - DEV/Programming/Swift/notes-useful-foundation.md
        - DEV/Programming/Swift/lecture-homework.md
        - DEV/Programming/Swift/parallel-for.md
      - C:
        - DEV/Programming/C/review.md
        - DEV/Programming/C/final.md
        - DEV/Programming/C/stdout-fflush.md
        - DEV/Programming/C/watch-matrix.md

  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - WEBSITE/build.md
    - WEBSITE/help.md
    - WEBSITE/test.md



# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/yyyxx6/yyyxx6.github.io # 右上角点击跳转的链接
repo_name: yyyxx6.github.io # 右上角的名字
## [bottom-left corner]
copyright: yyyxx6 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
      name: Bilibili | yyyxx6 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/yyyxx6
      name: GitHub | yyyxx6

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
